### ISSUE TITLE
se v3

### ISSUE THREAD

**Issue by suisseWalter** [dennisahlin/space-exploration-loves-bob#1]
space exploration has released a new version(3) and it makes this mod incompatible due to some changes with the naming of the research tree. I have tried to list all the changes I had to make to fix the compatibility. Are you interested in the list so that it is easier to fix the mod? or should I just run a pull request?

**Comment by dennisholmer** [comment]
@suisseWalter Please if you want create a PR if you can, I'll check it out and accept it :)

**Comment by suisseWalter** [comment]
I have created a PR with the necessary changes.
 I will probably do another one with some recipes for the delivery canon, when I find time to do so.

**Comment by dennisholmer** [comment]
Thank you!
Merge has been made and published to mods portal and you're mentioned as contributor in GitHub release :)

**Comment by dennisholmer** [comment]
https://github.com/dennisahlin/space-exploration-loves-bob/pull/2 Closed this issue
